defmodule Nomify.Repo.Migrations.AddDocuments do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :published_on, :date, null: false, default: fragment("CURRENT_DATE")
      add :security_level, :text, null: false, default: "low"
    end
  end

  def down do
    drop table(:documents)
  end
end
